class carritoscompras{
    constructor(C_pedido,C_serieproducto,D_cliente,Fecha,categoria,Precio){
        this._C_pedido = C_pedido;
        this._C_serieproducto = C_serieproducto;
        this._D_cliente = D_cliente;
        this._Fecha = Fecha;
        this._categoria=categoria;
        this._Precio=Precio;
    }
    
    agrupacion_productos(){
    
    }
    
    vaciar_carrito(){
    
    }
    
    confirmar_compra(){
    
    }
    
    calcular_compra(){
    
    }
    }
    